# Generated by Django 2.1.8 on 2020-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=11)),
                ('address', models.TextField()),
            ],
        ),
    ]
